version: 2
jobs:
  dependencies:
    docker:
    - image: node:10.16.0-alpine
    steps:
    - run:
        command: apk add git
    - checkout
    - restore_cache:
        key: dependency-cache-{{ checksum "package.json" }}
    - run:
        name: Npm Install
        command: npm install
    - save_cache:
        key: dependency-cache-{{ checksum "package.json" }}
        paths:
        - node_modules
  build:
    docker:
    - image: node:10.16.0-alpine
    steps:
    - run:
        command: apk add git
    - checkout
    - restore_cache:
        key: dependency-cache-{{ checksum "package.json" }}
    - run: npm build

  test-unit:
    docker:
    - image: node:10.16.0-alpine
    steps:
    - run:
        command: apk add git
    - checkout
    - restore_cache:
        key: dependency-cache-{{ checksum "package.json" }}
    - run:
        name: Unit Tests
        command: npm run test:unit:coverage
    - store_artifacts:
        path: tests/reports/unit/junit.xml
        prefix: tests
    - store_artifacts:
        path: tests/reports/unit/coverage
        prefix: coverage
    - store_test_results:
        path: tests/reports/unit
    - run:
        name: Coveralls
        command: export COVERALLS_GIT_COMMIT=$CIRCLE_SHA1 && npm run coveralls < tests/reports/unit/coverage/lcov.info

  build-container:
    docker:
    - image: node:10.16.0-alpine
    steps:
    - run:
        name: Install Git
        command: apk add git
    - checkout
    - restore_cache:
        key: dependency-cache-{{ checksum "package.json" }}
    - run:
        name: Build Container
        command: docker build -t jjmschofield/node-ts-starter:$CIRCLE_SHA1 .
    - run:
        name: Login
        command: docker login -u $DOCKER_HUB_USER $DOCKER_HUB_PASSWORD
    - run:
        name: Push Container
        command: docker push jjmschofield/node-ts-starter:$CIRCLE_SHA1


workflows:
  version: 2
  build_and_test:
    jobs:
    - dependencies
    - build:
        requires:
        - dependencies
    - test-unit:
        requires:
        - dependencies
