version: 2
jobs:
  build:
    docker:
    - image: node:10.16.0-alpine
    steps:
    - run:
        command: apk add git
    - checkout
    - restore_cache:
        key: dependency-cache-{{ checksum "package.json" }}
    - run:
        name: Npm Install
        command: npm install
    - save_cache:
        key: dependency-cache-{{ checksum "package.json" }}
        paths:
        - node_modules
  test-unit:
    docker:
    - image: node:10.16.0-alpine
    steps:
    - run:
        command: apk add git
    - checkout
    - run:
        name: Unit Tests
        command: npm run test:unit:coverage
    - store_artifacts:
        path: tests/reports/unit/junit.xml
        prefix: tests
    - store_artifacts:
        path: tests/reports/unit/coverage
        prefix: coverage

workflows:
  version: 2
  build_and_test:
    jobs:
    - build
    - test
